# This file was auto-generated from the MedTagger rules files.

cm_rStage = [
	r'''\b(?i)in situ\b''',
	r'''\b(?i)stage(\s+|\-)(I|1)(\s+|\-)a\b''',
	r'''\b(?i)stage(\s+|\-)(I|1)(\s+|\-)b\b''',
	r'''\b(?i)stage(\s+|\-)(II|2)(\s+|\-)a\b''',
	r'''\b(?i)stage(\s+|\-)(II|2)(\s+|\-)b\b''',
	r'''\b(?i)stage (III|3)(\s+|\-)a\b''',
	r'''\b(?i)stage(\s+|\-)(III|3)(\s+|\-)b\b''',
	r'''\b(?i)METASTASIS|Metastatic|mets\.|stage(\s+|\-)(IV|4)\b''',
	r'''\b(?i)Metastatic(\s+|\-)(Adenocarcinoma|Adenosquamous|Carconoid typical \/atypical|Large \/  larger neuroendocrine|Non(\s+|\-)small(\s+|\-)cell|Squamous|carcinoid|moderate differentiation)\b''',
	r'''\b(?i)(Metastatic|METASTASIS)(\s+\S+){0,10}\s+(cancer|tumor|neoplasm)\b''',
	r'''\b(?i)(cancer|tumor|neoplasm)(\s+\S+){0,10}\s+(Metastatic|METASTASIS)\b''',
	r'''\b(?i)(late(\s+|\-)Stage)\b''',
	r'''\b(?i)(early(\s+|\-)Stage)\b''',
	r'''\b(?i)(extensive)(\s+|\-)stage\b''',
	r'''\b(?i)(extensive)(\s+|\-)(bronchoalveolar carcinoma|cardinoma NOS|Adenocarcinoma|Non(\s*|-)small(\s*|-)cell|NSCC|NSCC NOS|Large cell neuroendocrine|large cell|LCNEC|neuroendocrine|LCNEM|Squamous|larger neuroendocrine|Large neuroendocrine|small(\s*|-)cell|Adenosquamous|typical carcinoid|atypical carcinoid|carcinoid|Large cell|Lepidic adenocarcinoma|Acinar adenocarcinoma|Papillary adenocarcinoma|Micropapillary adenocarcinoma|Solid adenocarcinoma|Invasive mucinous adenocarcinoma|Mixed invasive mucinous adenocarcinoma|Mixed invasive nonmucinous adenocarcinoma|Colloid adenocarcinoma|Fetal adenocarcinoma|Enteric adenocarcinoma|Minimally invasive adenocarcinoma|Preinvasive lesions|Adenocarcinoma in situ|Keratinizing squamous cell carcinoma|Nonkeratinizing squamous cell carcinoma|Basaloid squamous cell carcinoma|Squamous cell carcinoma in situ|Combined small cell|Large cell neuroendocrine|Combined large cell neuroendocrine|Preinvasive lesion|Sarcomatoid|Pleomorphic carcinoma|Spindle cell carcinoma|Giant cell carcinoma|Pulmonary blastoma|Lymphoepithelioma-like carcinoma|Nuclear protein in testis carcinoma|NUT carcinoma|Salivary gland-type|Mucoepidermoid carcinoma|Adenoid cystic carcinoma|Epithelial-myoepithelial carcinoma|BASAL CELL CARCINOMA NODULAR|BASAL CELL CARCINOMA NOS|BOWEN DISEASE|CHORDOMA|OSTEOSARCOMA|CHONDROBLASTIC OSTEOSARCOMA|CHONDROBLASTOMA(\s+\S+){0,3}MALIGNANT|MALIGNANT(\s+\S+){0,3} CHONDROBLASTOMA|lymphoma|dendritic cell neoplasm|Mast cell sarcoma|Mast cell sarcoma|leukemia|Langerhans cell histiocytosis|Histiocytic sarcoma|Langerhans cell sarcoma|myeloid neoplasms|panmyelosis|Polycythemia vera|Primary myelofibrosis|thrombocythemia|lymphoid neoplasms|myeloproliferative neoplasm|Refractory neutropenia|Refractory thrombocytopenia|Myeloid sarcoma|reticular cell tumor|MYELOMA|Kaposi's sarcoma|GLIOSARCOMA|GLIOMA(\s+\S+){0,3} MALIGNANT|MALIGNANT(\s+\S+){0,3} GLIOMA|DYSEMBRYOPLASTIC NEUROEPITHELIAL|MENINGIOMA|ASTROCYTOMA|MEDULLOBLASTOMA|ASTROBLASTOMA|MEDULLARY CARCINOMA|TERATOID|RHABDOID|CENTRAL NEUROCYTOMA|CENTRAL OSTEOSARCOMA|GLOMANGIOSARCOMA|ANGIOMATOID FIBROUS HISTIOCYT MALIGNANT|Angiomatoid fibrous histiocytoma)\b''',
	r'''\b(?i)(extensive)(\s+|\-)(Non(\s*|-)gradeable|poorly(\s*|-)differentiation|poor(\s*|-)differentiation|moderate(\s*|-)differentiation|well(\s*|-)differentiation|poorly(\s*|-)differentiated|moderately(\s*|-)differentiated|well(\s*|-)differentiated|grade(\s*|-)1|grade(\s*|-)2|grade(\s*|-)3|grade(\s*|-)4|grade(\s*|-)I|grade(\s*|-)II|grade(\s*|-)III|grade(\s*|-)IV|grade(\s*|-)V|undifferentiated|undifferentiation|high(\s*|-)grade|low(\s*|-)grade|intermediate(\s*|-)grade)\b''',
	r'''\b(?i)(IV|4)(\s+|\-)stage(\s+|\-)small(\s+|\-)cell\b''',
	r'''\b(?i)Metastatic(\s+|\-)small(\s+|\-)cell\b''',
	r'''\b(?i)Metastatic(\s+|\-)small(\s+|\-)cell\b''',
	r'''\b(?i)extensive(\s+|\-)stage\b''',
	r'''\b(?i)extensive(\s+|\-)stage\b''',
	r'''\b(?i)(Limited)(\s+|\-)stage\b''',
	r'''\b(?i)(Limited)(\s+|\-)(bronchoalveolar carcinoma|cardinoma NOS|Adenocarcinoma|Non(\s*|-)small(\s*|-)cell|NSCC|NSCC NOS|Large cell neuroendocrine|large cell|LCNEC|neuroendocrine|LCNEM|Squamous|larger neuroendocrine|Large neuroendocrine|small(\s*|-)cell|Adenosquamous|typical carcinoid|atypical carcinoid|carcinoid|Large cell|Lepidic adenocarcinoma|Acinar adenocarcinoma|Papillary adenocarcinoma|Micropapillary adenocarcinoma|Solid adenocarcinoma|Invasive mucinous adenocarcinoma|Mixed invasive mucinous adenocarcinoma|Mixed invasive nonmucinous adenocarcinoma|Colloid adenocarcinoma|Fetal adenocarcinoma|Enteric adenocarcinoma|Minimally invasive adenocarcinoma|Preinvasive lesions|Adenocarcinoma in situ|Keratinizing squamous cell carcinoma|Nonkeratinizing squamous cell carcinoma|Basaloid squamous cell carcinoma|Squamous cell carcinoma in situ|Combined small cell|Large cell neuroendocrine|Combined large cell neuroendocrine|Preinvasive lesion|Sarcomatoid|Pleomorphic carcinoma|Spindle cell carcinoma|Giant cell carcinoma|Pulmonary blastoma|Lymphoepithelioma-like carcinoma|Nuclear protein in testis carcinoma|NUT carcinoma|Salivary gland-type|Mucoepidermoid carcinoma|Adenoid cystic carcinoma|Epithelial-myoepithelial carcinoma|BASAL CELL CARCINOMA NODULAR|BASAL CELL CARCINOMA NOS|BOWEN DISEASE|CHORDOMA|OSTEOSARCOMA|CHONDROBLASTIC OSTEOSARCOMA|CHONDROBLASTOMA(\s+\S+){0,3}MALIGNANT|MALIGNANT(\s+\S+){0,3} CHONDROBLASTOMA|lymphoma|dendritic cell neoplasm|Mast cell sarcoma|Mast cell sarcoma|leukemia|Langerhans cell histiocytosis|Histiocytic sarcoma|Langerhans cell sarcoma|myeloid neoplasms|panmyelosis|Polycythemia vera|Primary myelofibrosis|thrombocythemia|lymphoid neoplasms|myeloproliferative neoplasm|Refractory neutropenia|Refractory thrombocytopenia|Myeloid sarcoma|reticular cell tumor|MYELOMA|Kaposi's sarcoma|GLIOSARCOMA|GLIOMA(\s+\S+){0,3} MALIGNANT|MALIGNANT(\s+\S+){0,3} GLIOMA|DYSEMBRYOPLASTIC NEUROEPITHELIAL|MENINGIOMA|ASTROCYTOMA|MEDULLOBLASTOMA|ASTROBLASTOMA|MEDULLARY CARCINOMA|TERATOID|RHABDOID|CENTRAL NEUROCYTOMA|CENTRAL OSTEOSARCOMA|GLOMANGIOSARCOMA|ANGIOMATOID FIBROUS HISTIOCYT MALIGNANT|Angiomatoid fibrous histiocytoma)\b''',
	r'''\b(?i)(Limited)(\s+|\-)(Non(\s*|-)gradeable|poorly(\s*|-)differentiation|poor(\s*|-)differentiation|moderate(\s*|-)differentiation|well(\s*|-)differentiation|poorly(\s*|-)differentiated|moderately(\s*|-)differentiated|well(\s*|-)differentiated|grade(\s*|-)1|grade(\s*|-)2|grade(\s*|-)3|grade(\s*|-)4|grade(\s*|-)I|grade(\s*|-)II|grade(\s*|-)III|grade(\s*|-)IV|grade(\s*|-)V|undifferentiated|undifferentiation|high(\s*|-)grade|low(\s*|-)grade|intermediate(\s*|-)grade)\b''',
	r'''\b(?i)stage(\s+|\-)(Limited)\b''',
	r'''\b(?i)stage(\s+|\-)(I|1) \b''',
	r'''\b(?i)stage(\s+|\-)(II|2) \b''',
	r'''\b(?i)stage(\s+|\-)(III|3) \b''',
	r'''\b(?i)AJCC\b''',
	r'''\b(?i)pT\)\:|primary tumor\:\s+\w{0,3}\s+(T)?(\d)?\s+\w{0,2}\b''',
	r'''\b(?i)pN\)\:|regional lymph nodes\:|category\:\s+\w{0,3}\s+(N)?(\d)?\s+\w{0,2}\b''',
	r'''\b(?i)pM\)\:|distant metastasis\b''',
]

cm_rSite = [
	r'''\b(?i)(chest|lung|trachea{0,5}|bronch\w{0,5}|lobar|lobe|spatum|pulmonary)(\s+\S+){0,20} (non(\-|\s+)small cell|Carcinoid|Adenosquamous|Adenocarcinoma|neuroendocrine|(squamous|squanous)\W? (\S+\s+){0,15}(carcinoma|cancer)|(carcinoma|cancer)\W? (\S+\s+){0,15}(squamous|squanous)|large cell)\b''',
	r'''\b(?i)(non(\-|\s+)small cell|Carcinoid|Adenosquamous|Adenocarcinoma|neuroendocrine|(squamous|squanous)\W? (\S+\s+){0,15}(carcinoma|cancer)|(carcinoma|cancer)\W? (\S+\s+){0,15}(squamous|squanous)|large cell)(\s+\S+){0,20} (chest|lung|trachea{0,5}|bronch\w{0,5}|lobar|lobe|spatum|pulmonary)\b''',
	r'''\b(?i)(lung cancer|lung ca |NSCLC)\b''',
	r'''\b(?i)( SCLC)\b''',
	r'''\b(?i)(chest|lung|trachea{0,5}|bronch\w{0,5}|lobar|lobe|spatum|pulmonary)(\s+\S+){0,20}\s+small(\-|\s+)cell\b''',
	r'''\b(?i)small(\-|\s+)cell(\s+\S+){0,20}\s+(chest|lung|trachea{0,5}|bronch\w{0,5}|lobar|lobe|spatum|pulmonary)\b''',
	r'''\b(?i)(isthmus uteri|endometrium|myometrium|fundus uteri|corpus uteri)\b''',
	r'''\b(?i)(Rectal|rectum|RECTOSIGMOID)\b''',
	r'''\b(?i)(anus|ANORECTUM|anal|anal canal)\b''',
	r'''\b(?i)(skin(\s+\S+){0,40} melanoma)\b''',
	r'''\b(?i)(melanoma(\s+\S+){0,40} skin)\b''',
	r'''\b(?i)melanoma\b''',
	r'''\b(?i)skin|DERMATOFIBROSARCOMA|BASAL CELL CARCINOMA NODULAR|BASAL CELL CARCINOMA NOS|BOWEN DISEASE\b''',
	r'''\b(?i)bone|cartilage|CHORDOMA|OSTEOSARCOMA|CHONDROBLASTIC OSTEOSARCOMA|CHONDROBLASTOMA(\s+\S+){0,3}MALIGNANT|MALIGNANT(\s+\S+){0,3} CHONDROBLASTOMA\b''',
	r'''(?i)small bowel|small intestin''',
	r'''(?i)prostate|prostatic''',
	r'''\b(?i)FLOOR OF MOUTH|GUM LOWER|GUM UPPER\b''',
	r'''\b(?i)Palatal|palate| oral |mouth|CHEEK MUCOSA\b''',
	r'''\b(?i)tonsil\b''',
	r'''\b(?i)lip\b''',
	r'''\b(?i)UROTHELIAL|ureter\b''',
	r'''\b(?i)LARYNX|laryngeal\b''',
	r'''\b(?i)meninges|eye|adnexa|spinal cord|cranial nerve|nerve\b''',
	r'''\b(?i)pharynx|pharyngeal\b''',
	r'''\b(?i)CERVIX|cervical\b''',
	r'''\b(?i)Mesothelioma|Kaposi's sarcoma|peripheral nerv|autonomic nerv|connective|soft tissue\b''',
	r'''\b(?i)GLOMANGIOSARCOMA|ANGIOMATOID FIBROUS HISTIOCYT MALIGNANT|Angiomatoid fibrous histiocytoma\b''',
	r'''\b(?i)THYROID\b''',
	r'''\b(?i)brain|GLIOSARCOMA|GLIOMA(\s+\S+){0,3} MALIGNANT|MALIGNANT(\s+\S+){0,3} GLIOMA|DYSEMBRYOPLASTIC NEUROEPITHELIAL|MENINGIOMA|ASTROCYTOMA|MEDULLOBLASTOMA|ASTROBLASTOMA|MEDULLARY CARCINOMA|TERATOID|RHABDOID|CENTRAL NEUROCYTOMA|CENTRAL OSTEOSARCOMA\b''',
	r'''\b(?i)(Follicular lymphoma|Non(\-|\s+)follicular lymphoma|Mature T\/NK(\-|\s+)cell lymphomas|Malignant immunoproliferative|B(\-|\s+)cell lymphomas|non(\-|\s+)Hodgkin lymphoma)\b''',
	r'''\b(?i)STOMACH|gastric\b''',
	r'''\b(?i)PANCREAS|PANCREATIC DUCT|ISLETS OF LANGERHANS|LANGERHANS ISLETS|pancreatic primary|pancreatic\b''',
	r'''\b(?i)STOMACH|gastric\b''',
	r'''\b(?i)MYELOMA\b''',
	r'''\b(?i)lymphoma|dendritic cell neoplasm|Mast cell sarcoma|Mast cell sarcoma|leukemia|Langerhans cell histiocytosis|Histiocytic sarcoma|Langerhans cell sarcoma|myeloid neoplasms|panmyelosis|Polycythemia vera|Primary myelofibrosis|thrombocythemia|lymphoid neoplasms|myeloproliferative neoplasm|Refractory neutropenia|Refractory thrombocytopenia|Myeloid sarcoma|reticular cell tumor\b''',
	r'''\b(?i)PERITONEUM|OMENTUM|MESENT\b''',
	r'''\b(?i)LIVER|hepatic\b''',
	r'''\b(?i)GALLBLADDER\b''',
	r'''\b(?i)BILE DUCT\b''',
	r'''\b(?i)PLEURA\b''',
	r'''\b(?i)BREAST\b''',
	r'''\b(?i)UTERUS\b''',
	r'''\b(?i)OVARY|ovarian\b''',
	r'''\b(?i)VULVA\b''',
	r'''\b(?i)TESTIS|TESTES|testicle\b''',
	r'''\b(?i)PENIS\b''',
	r'''\b(?i)BLADDER\b''',
	r'''\b(?i)KIDNEY|renal\b''',
	r'''\b(?i)RENAL PELVIS\b''',
	r'''\b(?i)ENDOCRINE\b''',
	r'''\b(?i)TONGUE\b''',
	r'''\b(?i)OROPHARYNX|OROPHARYN\w{0,5}\b''',
	r'''\b(?i)NASOPHARYNX|NASOPHARYN\w{0,5}\b''',
	r'''\b(?i)HYPOPHARYNX|HYPOPHARYN\w{0,5}\b''',
	r'''\b(?i)ESOPHAGUS|ESOPHAG\w{0,5}\b''',
	r'''\b(?i)COLON|COLON\w{0,5}\b''',
]

cm_excl = [
	r'''\b(?i)skin|stage(\s+\S+){0,3}\s+lesion\b''',
	r'''\b(?i)skin|stage(\s+\S+){0,3}\s+lesion\b''',
	r'''\b(?i)melanoma\b''',
	r'''\b(?i)(bone marrow|CARTILAGE FREE OF TUMOR)\b''',
	r'''\b(?i)FLOOR OF MOUTH|ulcer|\w{1,5}oral|oral chemotherapy|oral health\b''',
	r'''\b(?i)oral\b''',
	r'''\b(?i)arm|skin|ulcer\b''',
	r'''\b(?i)brain|eye lid\b''',
	r'''\b(?i)oropharynx|nasopharynx|hypopharynx|nasopharyngeal endoscopy\b''',
	r'''\b(?i)lung|small cell\b''',
	r'''\b(?i)parathyroid\b''',
	r'''\b(?i)colon|intestine\b''',
	r'''\b(?i)Follicular lymphoma|Non(\-|\s+)follicular lymphoma|Mature T\/NK(\-|\s+)cell lymphomas|Malignant immunoproliferative|B(\-|\s+)cell lymphomas|non(\-|\s+)Hodgkin lymphoma\b''',
	r'''\b(?i)renal insufficiency｜ckd|kidney disease|ulcer|history|chronic kidney failure|chronic kidney disease|acute kidney injury|chronic renal insufficiency|chronic renal failure|adrenal|renal insufficiency|ckd|kidney disease|ulcer|history|chronic kidney failure|chronic kidney disease|chronic renal failure|acute kidney injury|chronic renal insufficiency|insufficiency renal\b''',
	r'''\b(?i)non(\-|\s+)small\s+cell\b''',
	r'''\b(?i)oral intake\b''',
	r'''\b(?i)cirrhosis|liver biopsy|fibrosis\b''',
	r'''\b(?i)nasopharyngeal endoscopy\b''',
	r'''\b(?i)esophagitis\b''',
	r'''\b(?i)endocrine therapy|endocrine treatment\b''',
	r'''\b(?i)oral intake\b''',
]
