sections = {'plan':['action', 'actions', 'plan', 'plans',
                    'management plan', 'management', 
                    'current management', 'recommendation', 
                    'recommendations', 'p', 'rec', 'suggest',
                    'sw plan', 'consensus', 'mdt recommendations', 
                    'recommend', 'recs', 'for', 'referrals', 'ref',
                    'ot plan', 'case plan', 'assessment and plan', 
                    'intervention/recommendations', 'plan / future goals', 
                    'action / intervention', 'plan and investigations', 
                    'allied health referrals'],
            'exam': ['o\e', 'clinical examination', 'exam', 'today', 'current',
                     'on examination', 'examination', 'impression', 'consultation summary',
                     'physical assessment', 'nursing', 'physical exam', 
                     'oe', 'imp','skin assessment', 'abdo', 'cvs', 'pe',
                     'assessment', 'assess', 'investigations', 'on review', 
                     'i', 'investigation', 'ix', 'staging investigation', 
                     'current function', 'findings', 'ex', 'exn', 'o.e', 
                     'skin', 'currently', 'ecog', 'physical ax', 'a', 
                     'ecog score', 'o', 'now', 'pr', 'o/e', 'ax unit', 'pet scan', 'progress ct'],
            'results': ['outcome measures', 'results', 'pathology', 't', 'histology',
                        'histopath', 'vitals', 'result status', 'fbc', 'wt', 'bp',
                        'histopathology', 'path', 'bloods', 'temp', 'rr', 'bx','cxr',
                        'psa', 'biochem', 'chest', 'weight', 'bgls', 'o2sa', 'height',
                        'staging investigations', 'hb', 'bone scan', 'histo', 'ctpa',
                        'biochemistry', 'ph', 'hr', 'imaging', 'ct', 'ct scan', 
                        'pet', 'spo2', 'wbbs', 'ecg', 'wt hx', 'bmat', 'o2', 
                        'ctcap', 'ct cap', 'conclusion', 'full blood count', 
                        'creatinine', 'inr therapeutic range', 
                        'ecog performance status', 'summary of results'], 
            'diagnosis': ['dx', 'diagnosis', 'haematological diagnosis', 
                          'issues', 'main issues', 'issues identified', 
                          'diagnoses', 'haematological issue', 'issue',
                          'current issues'], 
            'social': ['smoking history', 'social', 'shx', 
                       'social history', 'smoking', 'alcohol', 'sochx', 
                       'alcohol history', 'sh', 'home environment', 
                       'family/spiritual concerns', 'relevant social history',
                       'social hx', 'etoh', 'alcohol intake', 'mobility',
                       'sx', 'support networks', 'transportation/financial'], 
            'nutrition_speech': ['nutrition dx', 'malnutrition', 'nutr dx', 
                                 'nutrition diagnosis', 'dietary', 'diet hx',
                                 'nutritional diagnosis', 'malnutrition score', 
                                 'diet', 'supplements', 'appetite', 'oral cavity',
                                 'current intake', 'intake', 'swallow', 'swallowing', 
                                 'requirements', 'eer', 'oral care', 'trismus', 'pharyngeal phase',
                                 'communication', 'voice', 'estimated requirements', 'diet history',
                                 'oral phase', 'oromotor', 'weight history', 'nutrition ax',
                                 'barriers to intake','nutrition-focused physical findings',
                                 'food/nutrition related history', 'pg-sga'],
            'radiotherapy': ['rad onc', 'rt', 'radonc'],
            'psych': ['psych', 'mental health', 'assessments|distress score', 'clinical psychology',
                      'ask if patient has been anxious/depressed in the past'],
            'surgery': ['surgical hx', 'surgical history', 'surgery', 'surg', 
                        'operation', 'pshx', 'surgeries', 'treatment/surgery', 
                        'past surgical history'],
            'history': ['past history', 'hx', 'medical hx', 'medical history', 
                        'mhx', 'pasthx', 'past medical history',
                        'medicals', 'history', 'pmhx', 'pmh', 'phx', 
                        'hpi', 'hpc', 'bg', 'hopc','hpoi', 
                        'history of presenting illness', 'previous treatment summary',
                        'history of the current problem'], 
            'comorbidities': ['comorbidities', 'medical comorbidities',
                              'hxpc', 'co-morbidities', 'medical co-morbidities'],
            'family': ['family history', 'fhx', 'family', 'fh', 
                       'family hx', 'famhx', 'family medical history'],
            'medication': ['drug hx', 'regular meds', 'medications',  'med', 'medications', 'rx',
                           'regular meds', 'meds', 'current meds', 'creams', 'dh', 'covid vaccine',
                           'current medications', 'medication', 'adt', 'conmed', 'concomitant meds', 
                           'dosing', 'reg meds', 'pneumonia vaccine', 'conmeds', 'other medications',
                           'regular medications'] ,
            'treatment': ['treatment', 'intervention', 'tx', 
                          'treatment summary', 'current treatment', 
                          'action/intervention'], 
            'education': ['education', 'discussed risk', 
                          'explained', 'discussion', 'long discussion', 
                          'communication', 'ed','discussed', 'advised'], 
            'demography': ['ethnicity', 'siblings', 'pregnancy history', 'background'],
            'allergies': ['allergies', 'ax', 'allergy'],
            'followup': ['follow up', 'fu', 'referral', 'followup'], 
            'symptoms': ['current sx', 'symptom history', 'pain', 'fatigue', 'symptoms', 'symptoms to report',
                         'current symptoms', 'neuropathy grade', 's', 'nausea', 'energy'],
            'summary': ['comment', 'summary', 'addendum', 'note', 'other', 'addit', 'additional'], 
            'progress': ['progress', 'progress note'], 
            'anthro': ['anthro', 'anthropometry', 'circumferential measurements'], 
            'clinical': ['clinical', 'med onc', 'medonc'],
            'monitor': ['monitor', 'monitoring'], 
            'toxicities': ['toxicities', 'toxicity', 'side effects', 'side effect', 'ae', 'aes'],
            'outcome': ['outcome', 'disease status'],
            'genitourinary_gynae': ['gu', 'gynae', 'ef', 'menstrual status', 'pregnancy', 'o&g', 'gynae hx'],
            'gastro': ['gi', 'bowel','bowels', 'stoma'],
            'respiratory': ['resp', 'respiratory'], 
            'contact': ['to', 'cc', 'subject', 'https', 're', 
                        'from', 'contact', 'sent', 'fax', 'subject number',
                        'phone', 'email', 'address', 'reported by'],
            'trial': ['trial', 'protocol number', 'visit', 'protocol title', 
                      'subject id', 'protocol', 'study']
            }

line_break = [{"LOWER": {"IN":["\n", "\n\n", "\n \n", "-"]}}]


sectionizer_attrs = {'exam': {'section_current': True},
                     'plan': {'section_hypothetical': True},
                     'family': {'section_family': True},
                     'history': {'section_historical':True},
                     'past_medical_history': {'section_historical': True},
                     'sexual_and_social_history': {'section_historical': True},
                     'family_history': {'section_family': True},
                     'patient_instructions': {'section_hypothetical': True},
                     'education': {'section_hypothetical': True},
                     'allergy': {'section_hypothetical': True}, 
                     'demography': {'section_historical': True},
                     'symptoms': {'section_current': True},
                     }
